#!/usr/bin/env bash

distro=$( grep -m 1 NAME /etc/os-release )
sudo pacman -S mesa-demos --noconfirm
if [[ ${distro} == *Arch* ]];
then
	sh distros/ARCH
fi

if [[ ${distro} == *Artix* ]];
then

	sh distros/ARTIX
fi

