#!/usr/bin/env bash

#this function detect init system in order to enabel tlp service
function init_detect () {
	PS=$( ps --pid 1 | grep -q systemd && echo 'systemd' || echo 'init' )
	if [[ $PS == *systemd* ]]; 
	then 
		sudo systemctl enable --now tlp
		IINIT = "DONE!"
	elif [[ $PS == *init* ]];
	then
		sudo rc-update add tlp
		sudo rc-service tlp start
	elif [[ $PS == *runit* ]];
	then

		ln -s /mnt/etc/runit/sv/tlp /mnt/etc/runit/runsvdir/default	
		IINIT = "DONE!"

	elif [[ $PS == *s6* ]];
	then
		
		s6-rc-bundle -c /etc/s6/rc/compiled add defaulttlp
		IINIT = "DONE!"
	else 
		INIT="Error Ocured!"; 
	fi
}

#Checks if you are instaling Arch or ARTIX because there are some difrences betwen the two
distro=$( grep -m 1 NAME /etc/os-release )
if [[ ${distro} == *Arch* ]];
then
	sh distros/ARCH
fi

if [[ ${distro} == *Artix* ]];
then
	sh distros/ARTIX
fi

#chceck if computer is a laptop
if [[ -f /sys/class/power_supply/BAT0 ]]
then
	
	yay -S tlp tlpui-git dmidecode --noconfirm #install power management software

	device=$(sudo dmidecode -s system-product-name) #detect if device is thinkpad 

	if [[ $device == *ThinkPad* ]] #if it is thinkaps it install some aditional software

	then
		yay -S tp_smapi acpi_call --noconfirm
	fi
init_detect #function call
fi
