#!/usr/bin/env bash
#-------------------------------------------------------------------------
#      _          _    __  __      _   _
#     /_\  _ _ __| |_ |  \/  |__ _| |_(_)__
#    / _ \| '_/ _| ' \| |\/| / _` |  _| / _|
#   /_/ \_\_| \__|_||_|_|  |_\__,_|\__|_\__|
#  Arch Linux Post Install Setup and Config
#-------------------------------------------------------------------------


#Entering Information for new install
echo "Please enter hostname:"
read hostname
echo "Please enter username:"
read username
echo "Please enter password:"
read -s password
echo "Please repeat password:"
read -s password2
# Check both passwords match
if [ "$password" != "$password2" ]; then
    echo "Passwords do not match"
    exit 1
fi

printf "hostname="$hostname"\n" > "install.conf"
printf "username="$username"\n" > "install.conf"
printf "password="$password"\n" > "install.conf"

#This segment check how much ram do you have instaled in your system and creates little bit bigger swap partition
mem_quantity=$(grep MemTotal /proc/meminfo | awk '{print $2}')
UNIT=$(grep MemTotal /proc/meminfo | awk '{print $3}')
mem_multipiler=$(echo $(($mem_quantity / 8)))
mem=$(echo $(($mem_multipiler + $mem_quantity)))

distro=$( grep -m 1 NAME /etc/os-release )
if [[ ${distro} == *Arch* ]];
then
	STRAP="pacstrap /mnt"
	CHROOT="arch-chroot /mnt "

fi
if [[ ${distro} == *Artix* ]];
then
	STRAP="basestrap /mnt"
	CHROOT="artix-chroot /mnt "
fi
echo $CHROOT

if [[ ${distro} == *Arch* ]];
then
	echo "-------------------------------------------------"
	echo "    Setting up mirrors for optimal download      "
	echo "-------------------------------------------------"
	pacman -Sy reflector --noconfirm
	cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
	reflector --verbose --latest 20 --sort rate --save /etc/pacman.d/mirrorlist
fi

echo -e "\nInstalling prereqs...\n$HR"
pacman -S --noconfirm gptfdisk btrfs-progs dialog

echo "-------------------------------------------------"
echo "-------select your disk to format----------------"
echo "-------------------------------------------------"
lsblk
echo "Please enter disk: (example /dev/sda)"
read DISK

echo "--------------------------------------"
echo -e "\nFormatting disk...\n$HR"
echo "--------------------------------------"


#Checking if selected disk is unmounted
umount ${DISK}*

# disk prep
sgdisk -Z ${DISK} # zap all on disk


if [[ -d "/sys/firmware/efi/efivars" ]]
then

	sgdisk -a 2048 -o ${DISK} # new gpt disk 2048 alignment
	if [[ ${DISK} == *nvme* ]];
	then
		echo "your disc standard is nvme"

		export BOOT="${DISK}p1"
		export ROOT="${DISK}p2"
		export SWAP="${DISK}p3"
	else
		echo "your disc standard is SATA"
		export BOOT="${DISK}1"
		export ROOT="${DISK}2"
		export SWAP="${DISK}3"
	fi
	# create partitions
	sgdisk -n 1:0:+1000M ${DISK}
	sgdisk -n 3:0:+$mem$unit ${DISK} 
	sgdisk -n 2:0:     ${DISK} 

	# set partition types
	sgdisk -t 1:ef00 ${DISK}
	sgdisk -t 2:8300 ${DISK}
	sgdisk -t 3:8200 ${DISK}

	# label partitions
	sgdisk -c 1:"UEFISYS" $BOOT
	sgdisk -c 2:"ROOT" $ROOT

	# make filesystems
	echo -e "\nCreating Filesystems...\n$HR"

	mkfs.vfat -F32 $BOOT
	mkfs.ext4 -L "ROOT" $ROOT
	mkswap $SWAP

	# mount target
	mkdir -p /mnt
	mount $ROOT /mnt
	mkdir -p /mnt/boot
	mount $BOOT /mnt/boot/
	swapon $SWAP




else	#if booted in legacy mode
	wipefs -fa ${DISK}
	if [[ ${DISK} == *nvme* ]];
	then
		echo "your disc standard is nvme"

		export ROOT="${DISK}p1"
		export SWAP="${DISK}p2"
	else
		echo "your disc standard is SATA"
		export ROOT="${DISK}1"
		export SWAP="${DISK}2"
	fi

	(
		echo o
		echo n
		echo p
		echo 1
		echo
		echo -${mem}K
		echo t
		echo 8
		echo 2
		echo w
	) | fdisk ${DISK}
	(
		echo n
		echo p
		echo 2
		echo
		echo
		echo w
	) | fdisk ${DISK}

	# make filesystems
	echo -e "\nCreating Filesystems...\n$HR"

	mkfs.ext4 -L "ROOT" $ROOT
	mkswap $SWAP

	# mount target
	mkdir -p /mnt
	mount $ROOT /mnt
	swapon $SWAP


fi

if [[ $distro == *Artix* ]]
then
	INIT=$(dialog --clear --title "Init System" --backtitle "BASH" --radiolist "Select init system to use by your system" 11 40 4  openrc "OpenRC init system" "on" runit "runiti init system" "off" s6 "s6 init system" "off"  --stdout)
	if [[ $INIT == *init* ]];
	then
		basestrap /mnt openrc elogind-openrc networkmanager networkmanager-openrc dhcpcd-openrc
		$CHROOT rc-update add connmand
		$CHROOT rc-update add NetworkManager 

	elif [[ $INIT  == *runit* ]];
	then
		$STRAP runit elogind-runit connman-runit connman-gtk networkmanager networkmanager-runit dhcpcd-runit
		ln -s /mnt/etc/runit/sv/connmand /mnt/etc/runit/runsvdir/default	
		$CHROOT ln -s /mnt/etc/runit/sv/NetworkManager /mnt/run/runit/service
	elif [[ $INIT == *s6* ]];
	then
		$CHROOT s6 elogind-s6 networkmanager networkmanager-s6 dhcpcd-s6
		$CHROOT s6-rc-bundle -c /etc/s6/rc/compiled add default connmand
		$CHROOT s6-rc-bundle -c /etc/s6/rc/compiled add default NetworkManager
	fi
fi

echo "--------------------------------------"
echo "-- Arch Install on Main Drive       --"
echo "--------------------------------------"

# This line checks CPU vendor. It will be usefull when we would want to install microcode for our cpu

$STRAP base base-devel linux-zen linux-firmware linux-zen-headers vim mesa-demos --noconfirm --needed
CPU=$( grep -m 1 vendor_id /proc/cpuinfo  | awk '{print $3} ') 
if [ $CPU = GenuineIntel ]
then
	pacstrap /mnt intel-ucode --noconfirm --needed
elif [ $CPU = AuthenticAMD ]
then
	pacstrap /mnt amd-ucode --noconfirm --needed
else
	echo "Can't recognize CPU vendor"
fi
	

genfstab -U /mnt >> /mnt/etc/fstab

#this is at this moment worthless
#Detecting Installed GPU and installing adequate drivers
GPU=$(lspci | grep -i --color "vga\|3d\|2d")
if [[ ${GPU} == *Radeon* ]];
then
	echo "your GPU vendor is AMD"
	$STRAP xf86-video-amdgpu
fi
if [[ ${GPU} == *Intel* ]];
then
	echo your GPU vendor is Intel
	$STRAP xf86-video-intel
fi
if [[ ${GPU} == *NV* ]];
then
	echo your GPU vendor is NVidia
	$STRAP nvidia
fi

echo "--------------------------------------"
echo "-- Preparing users locales and other--"
echo "--------------------------------------"

#Setting up User
$CHROOT useradd -mU -G wheel,uucp,video,audio,storage,games,input $username
echo "$username:$password" | $CHROOT chpasswd 
echo "root:$password" | $CHROOT chpasswd  
$CHROOT usermod -aG wheel,audio,video,optical,storage $username #adding suer to groups
# Add sudo no password rights
sed -i 's/^# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/' /mnt/etc/sudoers

#Setting hostname and hosts file
echo $hostname > /mnt/etc/hostname
echo "127.0.0.1   localhost" > /mnt/etc/hosts
echo "::1        	localhost" >> /mnt/etc/hosts
echo "127.0.1.1   $hostname.localdomain $hostname" >> /mnt/etc/hosts

#setting locale
echo "LANG=pl_PL.UTF-8" > /mnt/etc/locale.conf
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /mnt/etc/locale.gen
$CHROOT locale-gen
if [[ ${distro} == *Arch* ]];
then
$CHROOT timedatectl set-timezone Europe/Warsaw
fi
if [[ ${distro} == *Artix* ]];
then
$CHROOT  ln -sf /usr/share/zoneinfo/Poland /etc/localtime
fi
$CHROOT hwclock --systohc
# Set keymaps
#CHROOT localectl --no-ask-password set-keymap us

# PS varialbe stores information about current init system 
# I'm using it to detemine witch bootloader to install
# If its running systemd and computer is booted in efi mode then install systemd boot
# else install GRUB
PS=$( ps --pid 1 | grep -q systemd && echo 'systemd' || echo 'init' )
if [[ $PS == *systemd* ]]; 
then 
	echo "--------------------------------------"
	echo "--     Bootloader  Installation     --"
	echo "--------------------------------------"


	if [[ -d "/sys/firmware/efi/efivars" ]]
	then


		#setting up systemd bootloader entry
		$CHROOT bootctl --esp-path=/boot install
		touch /mnt/boot/loader/loader.conf
		echo "default arch-*" > /mnt/boot/loader/loader.conf
		touch /mnt/boot/loader/entries/arch.conf
		echo "title 	Arch Linux" > /mnt/boot/loader/entries/arch.conf
		echo "linux /vmlinuz-linux-zen" >> /mnt/boot/loader/entries/arch.conf

		#This statement chceck witch lines add to bootloader entry
		#It depends on CPU vendor witch was checked previously

		if [ $CPU = GenuineIntel ]
		then
			echo "initrd  /intel-ucode.img" >> /mnt/boot/loader/entries/arch.conf
			echo "initrd  /initramfs-linux-zen.img" >> /mnt/boot/loader/entries/arch.conf
			echo "options root=$ROOT rw resume=$SWAP" >> /mnt/boot/loader/entries/arch.conf
		elif [ $CPU = AuthenticAMD ]
		then
			echo "initrd  /amd-ucode.img" >> /mnt/boot/loader/entries/arch.conf
			echo "initrd  /initramfs-linux-zen.img" >> /mnt/boot/loader/entries/arch.conf
			echo "options root=$ROOT rw resume=$SWAP" >> /mnt/boot/loader/entries/arch.conf
		else
			echo "initrd  /initramfs-linux-zen.img" >> /mnt/boot/loader/entries/arch.conf
			echo "options root=$ROOT rw resume=$SWAP" >> /mnt/boot/loader/entries/arch.conf
		fi
	else
		$STRAP grub
		$CHROOT grub-install ${DISK}
		$CHROOT grub-mkconfig -o /boot/grub/grub.cfg
	fi


else # if not runing systemd install grub 
	$STRAP grub
	if [[ -d "/sys/firmware/efi/efivars" ]]
	then
		$STRAP efibootmgr 
		mkdir /mnt/boot/efi
		$CHROOT grub-install --target=x86_64-efi --bootloader-id=ARTIX --efi-directory=/boot
		$CHROOT grub-mkconfig -o /boot/grub/grub.cfg
	else
		$CHROOT grub-install ${DISK}
		$CHROOT grub-mkconfig -o /boot/grub/grub.cfg
	fi


fi

#setting up makepkg flags
nc=$(grep -c ^processor /proc/cpuinfo)
echo "You have " $nc" cores."
echo "-------------------------------------------------"
echo "Changing the makeflags for "$nc" cores."
sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j'$nc'"/g' /mnt/etc/makepkg.conf
echo "Changing the compression settings for "$nc" cores."
sed -i 's/COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -T '$nc' -z -)/g' /mnt/etc/makepkg.conf

#Networking enable

$STRAP networkmanager
if [[ $INIT == *systemd* ]]; 
then 
	sudo systemctl enable --now NetworkManager
elif [[ $INIT == *init* ]];
then
	$STRAP networkmanager-openrc networkmanager
	sudo rc-update add NetworkManager
	sudo rc-service NetworkManager start
elif [[ $INIT == *runit* ]];
then
                                                                         
	$STRAP networkmanager-runit
	ln -s /mnt/etc/runit/sv/NetworkManager /mnt/etc/runit/runsvdir/default	
                                                                         
elif [[ $INIT == *s6* ]];
then
	
	$STRAP networkmanager-s6
	s6-rc-bundle -c /etc/s6/rc/compiled add default NetworkManager
fi

#This line clone my personal postinstall script
git clone https://github.com/edwardbas-pl/arch-postinstall /mnt/home/$username/arch-postinstall
$CHROOT  chown -R $username /home/$username/arch-postinstall


#umount -R /mnt

POST=$(dialog --clear --title "Init System" --backtitle "BASH" --radiolist "Do you want to install addtional packages? (GUI and custom config)" 11 40 4  yes "Yesi want" "on" no "No I don't" "off" --stdout)
clear
if [[ $POST == *yes* ]]
then
	clear 
	echo "instaling additional programs"

	clear
	echo done

	echo downloading config files
	git clone https://github.com/edwardbas-pl/backup
	echo "coying config files"
	cd backup
	mkdir -p /mnt/home/$username/.config
	USER_HOME="/mnt/home/$username"
	CONFIG="$USER_HOME/.config"
	CONFIG_PATH=$(pwd)

	$chroot chown $username /home/$username/.config 
	mkdir -p $CONFIG/ranger
	mkdir -p $CONFIG/i3
	mkdir -p $CONFIG/polybar
	mkdir -p $HOME/.scripts
	#if on install medi wont be eough space  i should remove wallpapers folder from backup repo
	mkdir -p $USER_HOME/Pictures
	mkdir -p $USER_HOME/Pictures/Wallpapers
	mkdir -p $USER_HOME/.templates
	mkdir -p $CONFIG/kitty
	mkdir -p $CONFIG/dunst
	mkdir -p $CONFIG/picom
	mkdir -p $CONFIG/gtk-3.0
	mkdir -p $CONFIG/gtk-4.0
	mkdir -p $CONFIG/bspwm
	mkdir -p $CONFIG/sxhkd
	mkdir -p $CONFIG/dconf
	mkdir -p $CONFIG/dwm

	mkdir -p /etc/lightdm
	mkdir -p /usr/share/themes
	mkdir -p /usr/share/backgrounds
	mkdir -p /usr/share/icons

	cp -r $CONFIG_PATH/backgrounds/* 	/usr/share/backgrounds
	cp -r $CONFIG_PATH/backgrounds/* 	~/Pictures/Wallpapers
	cp -r $CONFIG_PATH/themes/*		/usr/share/themes/
	cp -r $CONFIG_PATH/icons/*		/usr/share/icons/

	cp $CONFIG_PATH/ranger/*		$CONFIG/ranger/
	cp $CONFIG_PATH/i3/*			$CONFIG/i3/ 
	cp $CONFIG_PATH/polybar/*		$CONFIG/polybar
	cp $CONFIG_PATH/kitty/*			$CONFIG/kitty
	cp $CONFIG_PATH/dunst/*			$CONFIG/dunst
	cp $CONFIG_PATH/picom/*			$CONFIG/picom
	cp $CONFIG_PATH/gtk-3.0/*		$CONFIG/gtk-3.0
	cp $CONFIG_PATH/gtk-4.0/*		$CONFIG/gtk-4.0
	cp $CONFIG_PATH/bspwm/*			$CONFIG/bspwm
	cp $CONFIG_PATH/sxhkd/*			$CONFIG/sxhkd
	cp $CONFIG_PATH/dconf/*			$CONFIG/dconf
	cp $CONFIG_PATH/dwm/*			$CONFIG/dwm/
	sudo cp $CONFIG_PATH/gtk-3.0/*		$CONFIG/gtk-3.0
	cp -r $CONFIG_PATH/.icons/		$USER_HOME/

	cp $CONFIG_PATH/polybar-scripts/*	$USER_HOME/.polybar-scripts/
	cp $CONFIG_PATH/scripts/*		$USER_HOME/.scripts/
	cp $CONFIG_PATH/bash_profile		$USER_HOME/.bash_profile
	cp $CONFIG_PATH/bashrc			$USER_HOME/.bashrc
	cp $CONFIG_PATH/vimrc			$USER_HOME/.vimrc
	cp $CONFIG_PATH/profile			$USER_HOME/.profile
	cp $CONFIG_PATH/xinitrc			$USER_HOME/.xinitrc
	cp $CONFIG_PATH/gtkrc-2.0		$USER_HOME/.gtkrc-2.0
	sudo cp $CONFIG_PATH/gtkrc-2.0		$USER_HOME/.gtkrc-2.0
	cp $CONFIG_PATH/compton.conf		$CONFIG/compton.conf
	sudo cp $CONFIG_PATH/lightdm/*		/etc/lightdm/

	$CHROOT chown -R /home/$username/*
	$CHROOT chgrp -R /home/$username/*

	clear
	#Generating wallpaper list for gnome-settings
	python << END

import os
import xml.etree.cElementTree as ET
workdir = os.getcwd()
os.chdir('/usr/share/backgrounds')
root = ET.Element("wallpapers")
def is_image(image_name):
    if image_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        return True
    else:
        print(image_name + ' is not supported image. It wil not be included into xml file' )
        return False

def add_to_xml(filename):
		wallpaper = ET.SubElement(root, "wallpaper", deleted="false")
		ET.SubElement(wallpaper, "name").text=filename
		ET.SubElement(wallpaper, "filename").text=filename
		ET.SubElement(wallpaper, "options").text='zoom'
		ET.SubElement(root, "pcolor").text='#ffffff'
		ET.SubElement(root, "scolor").text='#000000'
def recursive():
    ls = os.listdir(os.getcwd())
    for i in ls:
        is_dir = os.path.isdir(i)
        if is_dir == True:
            dir_before = os.getcwd()
            os.chdir(dir_before + '/' + i)
            recursive()
            os.chdir(dir_before)
            

        else:
            dir = (os.getcwd() + '/' + i)
            print(dir)
            #is_image(i)
            #add_to_xml(is_image(i))
            image = is_image(i)
            if image == True:
                add_to_xml(dir)


recursive()

tree = ET.ElementTree(root)
os.chdir(workdir)
tree.write("gnome-backgrounds.xml")
END
echo "DOtfiles copied"

elif [[ $POST == *no* ]]
then
	echo "You dont want to do postinstall"
fi

echo "--------------------------------------"
echo "--   SYSTEM READY FOR FIRST BOOT    --"
echo "--------------------------------------"
exit
